services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  rankingalgo:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - mysql
